### ISSUE TITLE
There should be a space in between the Discord username and the Minecraft username

### ISSUE THREAD

**Issue by Reevak05** [CamShaft54/IdleBot#12]
<img width="769" alt="Screen Shot 2021-01-01 at 5 51 43 PM" src="https://user-images.githubusercontent.com/47231296/103449248-8362f400-4c5a-11eb-8dfc-75e4bc243130.png">

**Comment by MetalTurtle18** [comment]
Please do not open superfluous issues. We are going to fix this.
