### ISSUE TITLE
Disable autoAKF option, language file & change afk command to toggle

### ISSUE THREAD

**Issue by pintoso** [Camshaft54/IdleBot#24]
1. **an option to disable idleTime** 
the plugin is really cool, but I want players to choose when they are afk

2. **language file**
it's not a problem for me, but many people stop using plugins because they don't have a translation file 

3. **change the afk command `/idlebot afk <true|false>` to `/idlebot afk`**
this makes it easy to create shortcut/alias
for example using MyCommand and typing `/afk` it will run `/idlebot afk`
that way I don't need to create a script and save player-data, etc. to just use `/afk` instead of `/afk true|false`

**Comment by MetalTurtle18** [comment]
1. On it
2. That is on the feature list, I'm not sure how soon it will be implemented but it will be eventually
3. Perhaps. Do you mean you want `/idlebot afk` to toggle on and off?

**Comment by pintoso** [comment]
yes `/idlebot afk` to toggle on and off

**Comment by MetalTurtle18** [comment]
Feature 1 and 2 *should be* implemented now but haven't been tested yet. I will test later

**Comment by MetalTurtle18** [comment]
@pintoso I am closing this issue since 1 & 3 have been implemented. The language support is already on our list so no need to keep this open. Of course if you have other feature requests or bugs make a new issue. Thanks
