### ISSUE TITLE
I wanna make a website for it

### ISSUE THREAD

**Issue by Reevak05** [CamShaft54/IdleBot#5]
aaaaaaaa I wrote out this whole issue already but didn't open a link in new tab so it got lost

I made a site of my fork to test it out. I wanted to make a PR to add the site to the main (this) repo but can't make one to a nonexistent branch. Could you: 1. create a new branch (preferably called `gh-pages`) so I can make a PR to it which I ~think~ am pretty sure will work or 2. give me write access to this repository (you can remove it after if that freaks you out) so I can make the site directly from this repo?

Here is the site for my fork:  https://reevak05.github.io/IdleBot/

P.S. I know it says maintained by Reevak05 at the bottom; it did that automatically I'm not trying to take credit for your work.

**Comment by MetalTurtle18** [comment]
https://github.com/CamShaft54/IdleBot/tree/gh-pages

**Comment by Reevak05** [comment]
if you are some crazy person viewing this who reads GitHub adventures instead of books, this saga continues in #6.
